- name: Update Grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  listen: update_grub
  notify: reboot_host

- name: Rebuilt initramfs
  ansible.builtin.command:
    cmd: dracut -f
  listen: rebuilt_initramfs
  notify: reboot_host

- name: Reboot host
  ansible.builtin.reboot:
  listen: reboot_host
