- name: Ensure dependencies are installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@virtualization"
    - "cockpit"
    - "cockpit-machines"
    - "cloud-init"

- name: Enable KVM service
  ansible.builtin.service:
    name: libvirtd
    state: started
