- name: Define VM
  community.libvirt.virt:
    name: "{{ vm_name }}"
    command: define
    xml: "{{ lookup('template', 'kvm_machine.xml.j2') }}"

- name: Start VM
  community.libvirt.virt:
    name: "{{ vm_name }}"
    state: running
