- name: Ensure dependencies
  ansible.builtin.import_tasks:
    file: _ensure_dependencies.yaml

- name: Setup cloud-init
  ansible.builtin.import_tasks:
    file: _setup_cloud_init_config.yaml

- name: Setup base image
  ansible.builtin.import_tasks:
    file: _setup_base_image.yaml

- name: Create images
  ansible.builtin.import_tasks:
    file: _create_images.yaml

- name: Start the VM
  ansible.builtin.import_tasks:
    file: _start_vm.yaml
