ansible_host: "homelab-server.home"
ansible_user: root
ansible_ssh_private_key_file: "/runner/.ssh/id_ed25519"

vm_image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
