- name: Install Containerd (CRI)
  ansible.builtin.package:
    name: containerd
    state: present

- name: Create Containerd config directory
  ansible.builtin.file:
    path: /etc/containerd/
    state: directory

- name: Deploy config
  ansible.builtin.copy:
    src: containerd.toml
    dest: /etc/containerd/config.toml
  notify: Restart Containerd


