- name: Load Kernel modules
  ansible.builtin.import_tasks:
    file: _load_kernel_modules.yaml

- name: Configure networking
  ansible.builtin.import_tasks:
    file: _configure_networking.yaml

- name: Install CRI
  ansible.builtin.import_tasks:
    file: _install_cri.yaml

- name: Install kube
  ansible.builtin.import_tasks:
    file: _install_kube.yaml

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
