- name: Testing play
  hosts: homelab
  tasks:
    - name: Log facts
      ansible.builtin.debug: var=ansible_facts

    - name: Create test file
      ansible.builtin.copy:
        dest: /tmp/hello_world.txt
        content: |
          Hello world
