- name: Add Hashicorp repository for Redhat family
  when: ansible_os_family == "RedHat"
  become: true
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: "0644"

- name: Install Packer
  become: true
  ansible.builtin.package:
    name: packer
    state: present
